### ISSUE TITLE
Newer Spreadtrum/Unisoc .pac support

### ISSUE THREAD

**Issue by HemanthJabalpuri** [AndroidDumps/Firmware_extractor#19]
.pac files for newer devices having super partition have size of greater than 4GiB and can't be handled by existing pacextractor.
So what about using https://github.com/jingpad-bsp/vendor_sprd_tools_ota/blob/58ae4a1775854158a48ab30b0d9d006c043950e7/otatool/prebuilts/linux-x86/ota/pac_tools/unpac_perl/unpac.pl @deadman96385 ?

Devices having .pac files greater than 4GiB that I know are Realme C11 2021, Realme C21Y, Realme C35.

**Comment by HemanthJabalpuri** [comment]
I converted that Perl to Python with my basic knowledge. https://github.com/HemanthJabalpuri/pacextractor/blob/eb3ac077e07fb084a7f7c56e8983434e75b86168/python/pacExtractor.py
I don't know if it is a correct conversion or not but I tried.

**Comment by deadman96385** [comment]
Looks promising, will take a look at this hopefully in the next few days.

**Comment by HemanthJabalpuri** [comment]
Fixed with https://github.com/AndroidDumps/Firmware_extractor/commit/d44a0d1a324b8fdb701abe6a0b2cc9c0fa8ca231
