### ISSUE TITLE
Suggestion: consider using `otadump` in place of `payload-dumper-go`

### ISSUE THREAD

**Issue by ajeetdsouza** [AndroidDumps/Firmware_extractor#31]
Hi! I'm the author of [`otadump`](https://github.com/crazystylus/otadump). It works similar to `payload-dumper-go`, but is [2-5x faster](https://github.com/crazystylus/otadump#benchmarks) and [verifies extracted partitions](https://github.com/crazystylus/otadump#features) to be extra safe.

I recently posted on Reddit and a commenter [mentioned](https://www.reddit.com/r/androiddev/comments/12gdq6j/comment/jflzvr0/) that this tool might be useful to you. Would you accept a PR to integrate `otadump` into your codebase?

Thanks!

CC: @crazystylus

**Comment by deadman96385** [comment]
Hello, sounds like a nice improvement, we would definitely accept a PR replacing payload-dumper-go!

**Comment by crazystylus** [comment]
Hi @deadman96385 ,
Can we refer to [this PR](https://github.com/AndroidDumps/Firmware_extractor/pull/25) or do we need to make any additional changes?

**Comment by deadman96385** [comment]
Ah sorry about that, missed it had already gone through.

**Comment by ajeetdsouza** [comment]
@deadman96385 I believe this issue was closed incorrectly. The new PR (https://github.com/AndroidDumps/Firmware_extractor/pull/32) provides a very significant performance boost over the old implementation. Would you be able to take another look?
