### ISSUE TITLE
BRUH: This type of firmwares not supported(pac file)

### ISSUE THREAD

**Issue by ghost** [AndroidDumps/Firmware_extractor#38]
I tried to use the tool on a pac and failed unpacked it using toll in tools directory and try tool fail used super.img and fail what do I do (btw I use termux and I didn't install some dependencies )

**Comment by OneNormalUsername** [comment]
Your issue misses all the following:
- Actual OS version
- A list of which dependencies were not installed and why
- A download link to the PAC file to try to reproduce the issue
