### ISSUE TITLE
Make guide on how to get dump from factory image

### ISSUE THREAD

**Issue by yankarinRG** [AndroidDumps/Firmware_extractor#4]
It's not very clear how to get the nicely extracted and usable dump from the output of Firmware_extractor (boot.img, dtbo.img, product.img, system.img, vendor.img).

**Comment by ShivamKumarJha** [comment]
Dumpyara script extracts those images

**Comment by yankarinRG** [comment]
Thank you, I wasn't aware of this script.
I get these two errors:
- head: error reading 'home/user/dumpyara/input/out': Is a directory

and
- ERROR: home/user/dumpyara/input/out/boot.img' : Can not open this file as archive
- ERROR: home/user/dumpyara/input/out/dtbo.img' : Can not open this file as archive
- ERROR: home/user/dumpyara/input/out/product.img' : Can not open this file as archive
- ERROR: home/user/dumpyara/input/out/system.img' : Can not open this file as archive
- ERROR: home/user/dumpyara/input/out/vendor.img' : Can not open this file as archive

Thank you for the help!

**Comment by ShivamKumarJha** [comment]
Can i see the full log?
BTW we've already dumped that firmware and had no such problem.

**Comment by yankarinRG** [comment]
Of course, [here](https://pastebin.com/dr3TYeQm)'s the command line log:

**Comment by ShivamKumarJha** [comment]
> Of course, [here](https://pastebin.com/dr3TYeQm)'s the command line log.
> I'm using a factory image, not a full OTA image. Is that ok?
You are giving directory as argument which is not supported.

`bash dumpyara.sh "<path to compressed OTA file>"`

**Comment by yankarinRG** [comment]
Ohh okay I thought I had to use Firmware_extractor first and then dumpyara.

**Comment by AyaanSaleemMalik** [comment]
Extracting modem partition
No system build*.prop found, pushing failed? Getting this in all ROMs and stock firmware files.
