### ISSUE TITLE
extraction fails

### ISSUE THREAD

**Issue by mylove90** [AndroidDumps/Firmware_extractor#41]
Hello,

i am trying to extract Samsung Galaxy A15 rom but it looks like there is a problem with super partition extraction

I am using an ARM64 Linux server to do this...please tell if thats the problem. 

ubuntu@instance-20231104-0510:~/Firmware_extractor$ neofetch
            .-/+oossssoo+/-.               ubuntu@instance-20231104-0510
        `:+ssssssssssssssssss+:`           -----------------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.4 LTS aarch64
    .ossssssssssssssssssdMMMNysssso.       Host: KVM Virtual Machine virt-4.
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.5.0-1023-oracle
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 11 hours, 27 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1092 (dpkg), 6 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/2
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: (4)
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: 00:01.0 Red Hat, Inc. Virtio
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 272MiB / 23981MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

ubuntu@instance-20231104-0510:~/Firmware_extractor$ wget https://07-samfw.cloud/v2/IxJCDiMnLgE1MRoULy8HODQvMxwPCB4lFzssIDs2ByAzMUEgOzEUQDMQMCMBOyw/LjEzNTxAKQIeJSkGMjYUAh4bBy0PCDMaARYhNh4sLhoyOwI/MgAvPDgxBhoDLy88LghBIyMbHhI1EQgkMiUeBTILBxI8LwgfAQQxMCMlFTE7Jy8dOwc+CS84BkIeCzwGHgM8FCMkNDEjCxVACTghHzInDQYuFx8rIwAvJCFAMxE8EQY5NRshDjURPho0ES8kNRYhOR44LwsJEQc5NBsjKyEAPg4hAAYsLjgeLDQRHg4yJTMsMiUNKzwAPh8mGzk5FyUzDTUHQQEuByADISxBIwMnOUANQAokMzYCICMXPjkDFzA1CS8pDTsxHhwzQAZCOzEHHjMsNCsNMT4eODAeHgk7CAYeAy8nODFBHDMwPiAjAzswMywpPC8DQQQXCDsxOAAhKTw/FD01OCBCJicxMB5ANDkPOzACO0AzJA8lMwU4ACwkLiUHHBIvKS07By8eNSRBAB4nIRcjOAZCIwM0BgEDIh0jJCIAAQ0TEw==
--2024-06-22 17:33:41--  https://07-samfw.cloud/v2/IxJCDiMnLgE1MRoULy8HODQvMxwPCB4lFzssIDs2ByAzMUEgOzEUQDMQMCMBOyw/LjEzNTxAKQIeJSkGMjYUAh4bBy0PCDMaARYhNh4sLhoyOwI/MgAvPDgxBhoDLy88LghBIyMbHhI1EQgkMiUeBTILBxI8LwgfAQQxMCMlFTE7Jy8dOwc+CS84BkIeCzwGHgM8FCMkNDEjCxVACTghHzInDQYuFx8rIwAvJCFAMxE8EQY5NRshDjURPho0ES8kNRYhOR44LwsJEQc5NBsjKyEAPg4hAAYsLjgeLDQRHg4yJTMsMiUNKzwAPh8mGzk5FyUzDTUHQQEuByADISxBIwMnOUANQAokMzYCICMXPjkDFzA1CS8pDTsxHhwzQAZCOzEHHjMsNCsNMT4eODAeHgk7CAYeAy8nODFBHDMwPiAjAzswMywpPC8DQQQXCDsxOAAhKTw/FD01OCBCJicxMB5ANDkPOzACO0AzJA8lMwU4ACwkLiUHHBIvKS07By8eNSRBAB4nIRcjOAZCIwM0BgEDIh0jJCIAAQ0TEw==
Resolving 07-samfw.cloud (07-samfw.cloud)... 188.114.97.3, 188.114.96.3, 2a06:98c1:3120::3, ...
Connecting to 07-samfw.cloud (07-samfw.cloud)|188.114.97.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7203139280 (6.7G) [application/zip]
Saving to: ‘FD01OCBCJicxMB5ANDkPOzACO0AzJA8lMwU4ACwkLiUHHBIvKS07By8eNSRBAB4nIRcjOAZCIwM0BgEDIh0jJCIAAQ0TEw==’

FD01OCBCJicxMB5ANDk 100%[================>]   6.71G  55.5MB/s    in 94s

2024-06-22 17:35:16 (72.7 MB/s) - ‘FD01OCBCJicxMB5ANDkPOzACO0AzJA8lMwU4ACwkLiUHHBIvKS07By8eNSRBAB4nIRcjOAZCIwM0BgEDIh0jJCIAAQ0TEw==’ saved [7203139280/7203139280]

ubuntu@instance-20231104-0510:~/Firmware_extractor$ mv FD01OCBCJicxMB5ANDkPOzACO0AzJA8lMwU4ACwkLiUHHBIvKS07By8eNSRBAB4nIRcjOAZCIwM0BgEDIh0jJCIAAQ0TEw\=\= SAMFW.COM_SM-A155F_BOG_A155FXXU2BXE4_fac.zip                                 ubuntu@instance-20231104-0510:~/Firmware_extractor$ ./extractor.sh SAMFW.COM_SM-A155F_BOG_A155FXXU2BXE4_fac.zip                                           Create Temp and out dir                                                      Extracting firmware on: /home/ubuntu/Firmware_extractor/out                  AP tarmd5 detected                                                           Extracting tarmd5
Extracting images...
removed 'AP_A155FXXU2BXE4_A155FXXU2BXE4_MQB81097780_REV00_user_low_ship_MULTI_CERT_meta_OS14.tar.md5'
Extracted AP_A155FXXU2BXE4_A155FXXU2BXE4_MQB81097780_REV00_user_low_ship_MULTI_CERT_meta_OS14.tar.md5
removed 'BL_A155FXXU2BXE4_A155FXXU2BXE4_MQB81097780_REV00_user_low_ship_MULTI_CERT.tar.md5'
Extracted BL_A155FXXU2BXE4_A155FXXU2BXE4_MQB81097780_REV00_user_low_ship_MULTI_CERT.tar.md5
removed 'CP_A155FXXU2BXE2_CP26527504_MQB80529102_REV00_user_low_ship_MULTI_CERT.tar.md5'
Extracted CP_A155FXXU2BXE2_CP26527504_MQB80529102_REV00_user_low_ship_MULTI_CERT.tar.md5
removed 'CSC_OXM_A155FOXM2BXE3_QB80611278_REV00_user_low_ship_MULTI_CERT.tar.md5'
Extracted CSC_OXM_A155FOXM2BXE3_QB80611278_REV00_user_low_ship_MULTI_CERT.tar.md5
removed 'HOME_CSC_OXM_A155FOXM2BXE3_QB80611278_REV00_user_low_ship_MULTI_CERT.tar.md5'
Extracted HOME_CSC_OXM_A155FOXM2BXE3_QB80611278_REV00_user_low_ship_MULTI_CERT.tar.md5
removed 'boot.img.lz4'
Extracted boot.img.lz4
removed 'cache.img.lz4'
Extracted cache.img.lz4
removed 'dpm-verified.img.lz4'
Extracted dpm-verified.img.lz4
removed 'dtbo.img.lz4'
Extracted dtbo.img.lz4
removed 'efuse.img.lz4'
Extracted efuse.img.lz4
removed 'gz-verified.img.lz4'
Extracted gz-verified.img.lz4
removed 'lk-verified.img.lz4'
Extracted lk-verified.img.lz4
removed 'mcupm-verified.img.lz4'
Extracted mcupm-verified.img.lz4
removed 'md1img.img.lz4'
Extracted md1img.img.lz4
removed 'misc.bin.lz4'
Extracted misc.bin.lz4
removed 'omr.img.lz4'
Extracted omr.img.lz4
removed 'optics.img.lz4'
Extracted optics.img.lz4
removed 'param.bin.lz4'
Extracted param.bin.lz4
removed 'pi_img-verified.img.lz4'
Extracted pi_img-verified.img.lz4
removed 'preloader.img.lz4'
Extracted preloader.img.lz4
removed 'prism.img.lz4'
Extracted prism.img.lz4
removed 'recovery.img.lz4'
Extracted recovery.img.lz4
removed 'scp-verified.img.lz4'
Extracted scp-verified.img.lz4
removed 'spmfw-verified.img.lz4'
Extracted spmfw-verified.img.lz4
removed 'sspm-verified.img.lz4'
Extracted sspm-verified.img.lz4
removed 'super.img.lz4'
Extracted super.img.lz4
removed 'tee-verified.img.lz4'
Extracted tee-verified.img.lz4
removed 'tzar.img.lz4'
Extracted tzar.img.lz4
removed 'uh.bin.lz4'
Extracted uh.bin.lz4
removed 'up_param.bin.lz4'
Extracted up_param.bin.lz4
removed 'userdata.img.lz4'
Extracted userdata.img.lz4
removed 'vbmeta.img.lz4'
Extracted vbmeta.img.lz4
removed 'vbmeta_system.img.lz4'
Extracted vbmeta_system.img.lz4
removed 'vendor_boot.img.lz4'
Extracted vendor_boot.img.lz4
Creating super.img.raw ...
Extract failed

**Comment by ant14181** [comment]
Yes, this is most probably related to your system being ARM64.

**Comment by mylove90** [comment]
> Yes, this is most probably related to your system being ARM64.

yea... I was able to extract it later when i installed box64 package or something like that
