### ISSUE TITLE
 No system build*.prop found, pushing

### ISSUE THREAD

**Issue by AyaanSaleemMalik** [AndroidDumps/Firmware_extractor#5]
Getting this in almost all ROMs.

Here are the logs 

Scissordragonboy@ten:~/dumpyara$ sudo bash dumpyara.sh ~/rom/miui_MIMAX2Global_V10.3.1.0.NDDMIXM_bb9a580717_7.1.zip
GitHub token not found. Dumping just locally...
Submodule 'tools/oppo_ozip_decrypt' (https://github.com/bkerler/oppo_ozip_decrypt.git) registered for path 'tools/oppo_ozip_decrypt'
Submodule 'tools/update_payload_extractor' (https://github.com/gmrt/update_payload_extractor.git) registered for path 'tools/update_payload_extractor'
Cloning into 'tools/oppo_ozip_decrypt'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 115 (delta 44), reused 41 (delta 14), pack-reused 10
Receiving objects: 100% (115/115), 29.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (46/46), done.
Checking connectivity... done.
Submodule path 'tools/oppo_ozip_decrypt': checked out 'f27894b8cdc90715d2f4eaad429e72e4980d0606'
Cloning into 'tools/update_payload_extractor'...
remote: Enumerating objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
Submodule path 'tools/update_payload_extractor': checked out '4632cf0a0a6db27cce20c25cb40fc469a2c8e9aa'
Create Temp and out dir
Extracting firmware on: /home/Scissordragonboy/dumpyara/working/miui_MIMAX2Global_V10.3.1.0.NDDMIXM_bb9a580717_7.1
tz.mbn detected for tz
NON-HLOS detected for modem
Aonly OTA detected
Extracting system
boot extracted
Extracting system partition
Extracting modem partition
No system build*.prop found, pushing canceled.

**Comment by ShivamKumarJha** [comment]
Did you run [setup.sh](https://github.com/AndroidDumps/dumpyara/blob/master/setup.sh) before ?

Also send output of   
`ls /home/Scissordragonboy/dumpyara/working/miui_MIMAX2Global_V10.3.1.0.NDDMIXM_bb9a580717_7.1 `

**Comment by AyaanSaleemMalik** [comment]
I run bash setup.sh
bash dumpyara.sh <ROM dir>

**Comment by AyaanSaleemMalik** [comment]
Last login: Wed Nov  6 10:04:02 2019 from 139.167.232.54
Scissordragonboy@ten:~$ cd dumpyara
Scissordragonboy@ten:~/dumpyara$ bash setup.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
device-tree-compiler is already the newest version (1.4.0+dfsg-2).
gawk is already the newest version (1:4.1.3+dfsg-0.1).
liblzma-dev is already the newest version (5.1.1alpha+20120614-2ubuntu2).
unzip is already the newest version (6.0-20ubuntu1).
zip is already the newest version (3.0-11).
aria2 is already the newest version (1.19.0-1build1).
arj is already the newest version (3.10.22-14).
axel is already the newest version (2.5-2).
cabextract is already the newest version (1.6-1).
liblz4-tool is already the newest version (0.0~r131-2ubuntu2).
mpack is already the newest version (1.6-8).
unace is already the newest version (1.2b-14).
uudeview is already the newest version (0.5.20-3.4).
p7zip-rar is already the newest version (9.20.1~ds.1-4).
rar is already the newest version (2:5.3.b2-1).
file-roller is already the newest version (3.16.5-0ubuntu1.3).
sharutils is already the newest version (1:4.15.2-1ubuntu0.1).
brotli is already the newest version (1.0.3-1ubuntu1~16.04.1).
p7zip-full is already the newest version (9.20.1~dfsg.1-4.2ubuntu0.1).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
unrar is already the newest version (1:5.3.2-1+deb9u1build0.16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: backports.lzma in /home/Scissordragonboy/.local/lib/python2.7/site-packages (0.0.14)
Requirement already satisfied: protobuf in /home/Scissordragonboy/.local/lib/python2.7/site-packages (3.10.0)
Requirement already satisfied: pycrypto in /home/Scissordragonboy/.local/lib/python2.7/site-packages (2.6.1)
Requirement already satisfied: setuptools in /home/Scissordragonboy/.local/lib/python2.7/site-packages (from protobuf) (41.6.0)
Requirement already satisfied: six>=1.9 in /home/Scissordragonboy/.local/lib/python2.7/site-packages (from protobuf) (1.12.0)
Scissordragonboy@ten:~/dumpyara$ bash dumpyara.sh ~/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a.tgz
GitHub token not found. Dumping just locally...
Fetching submodule tools/oppo_ozip_decrypt
Fetching submodule tools/update_payload_extractor
Already up-to-date.
Create Temp and out dir
Extracting firmware on: /home/Scissordragonboy/dumpyara/working/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a
non AP tar detected
Create Temp and out dir
Extracting firmware on: /home/Scissordragonboy/dumpyara/working/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a
tz.mbn detected for tz
NON-HLOS detected for modem
Image detected
boot extracted
Extracting system partition
Extracting cust partition
Extracting modem partition
No system build*.prop found, pushing cancelled!
Scissordragonboy@ten:~/dumpyara$ cd working
Scissordragonboy@ten:~/dumpyara/working$ ls
oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a
Scissordragonboy@ten:~/dumpyara/working$ cd oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a
Scissordragonboy@ten:~/dumpyara/working/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a$ ls
all_files.txt  board-info.txt  boot  bootdts  bootimg  boot.img  cust  modem  system  tz.img
Scissordragonboy@ten:~/dumpyara/working/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a$ cd system
Scissordragonboy@ten:~/dumpyara/working/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a/system$ ls
Scissordragonboy@ten:~/dumpyara/working/oxygen_global_images_9.6.27_20190627.0000.00_7.1_global_fc70f8eb0a

**Comment by ShivamKumarJha** [comment]
as discussed on telegram, your problem is due to older version of 7z. upgrade it
