### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by mrmazakblu** [AndroidDumps/Firmware_extractor#6]
gawk needed to run . It is not listed in requirements
"./extractor.sh: line 156: gawk: command not found"

And

"Package lz4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'lz4' has no installation candidate"

on default repo from ubuntu.

**Comment by ShivamKumarJha** [comment]
https://github.com/AndroidDumps/dumpyara/blob/master/setup.sh
