### ISSUE TITLE
protobuf error extracting

### ISSUE THREAD

**Issue by xstefen** [AndroidDumps/Firmware_extractor#9]
on my debian testing system, protobuf was finally satisfied by installing apt package 'python3-protobuf' else would error something about missing google.protobuf, the pip packages were installed 

solution: add 'python3-protobuf' to list of dependencies to install

**Comment by ShivamKumarJha** [comment]
yes as ozip decrypt script uses python3. will update

**Comment by xstefen** [comment]
any idea what could be causing this:

Extracting 'oem_stanvbk.img'
Extracting 'reserve.img'
Extracting 'india.img'
Traceback (most recent call last):
  File "/home/xstefen/android/dumpyara/extract-dtb/extract-dtb.py", line 142, in <module>
    split(args)
  File "/home/xstefen/android/dumpyara/extract-dtb/extract-dtb.py", line 92, in split
    os.rename(os.path.join(filepath),
FileNotFoundError: [Errno 2] No such file or directory: '/home/xstefen/android/dumpyara/working/OnePlus6TOxygen_34_OTA_045_all_2004142152_e822ca326/bootimg/04_dtbdump.dtb' -> '/home/xstefen/android/dumpyara/working/OnePlus6TOxygen_34_OTA_045_all_2004142152_e822ca326/bootimg/04_dtbdump_rMbtE/)6<.dtb'

boot extracted
dtbo extracted
Extracting system partition
